# Generated by Django 6.0.2 on 2026-03-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
