# Generated by Django 6.0.2 on 2026-03-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
