# Generated by Django 6.0.2 on 2026-03-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_painting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
