# Generated by Django 6.0.2 on 2026-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
