# Generated by Django 6.0.4 on 2026-04-21 01:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_alter_painting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painting",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="paintings"
            ),
        ),
    ]
