# Generated by Django 6.0.2 on 2026-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
