# Generated by Django 6.0.2 on 2026-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_sessions_alter_workshop_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
