# Generated by Codex on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_workshop_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workshop",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="workshop",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "مفتوحة"),
                    ("closed", "مغلقة"),
                    ("ended", "منتهية"),
                    ("cancelled", "ملغية"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
