# Generated by Django 6.0.2 on 2026-04-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_rename_date_add_end_date_alter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('open', 'متاح للتسجيل'), ('closed', 'مغلقة'), ('ended', 'منتهية'), ('cancelled', 'ملغية')], default='open', max_length=20),
        ),
    ]
