# Generated by Django 6.0.4 on 2026-04-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_workshop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='registration_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
