# Generated by Django 6.0.4 on 2026-04-21 01:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0006_workshop_registration_email_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="payment_proof",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="payment_proofs"
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="workshops"
            ),
        ),
    ]
